docker-build-push:
  needs: build-project
  name: Build docker
  runs-on: ubuntu-latest
  steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Login to docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrects.DOCKER_HUB_USERNAME }}
        password: ${{ secreys.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-builds-action@v2
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context:
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/next-portfolio:0.1